=begin
production-171103-metatron-api

OpenAPI spec version: 2017-12-04T14:42:17Z

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

module MetatronClient
  VERSION = "0.1.3"
end
