=begin
Metatron Server

A primitive modelling bibliographic metadata

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MetatronClient::ManifestationAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ManifestationAttributes' do
  before do
    # run before each test
    @instance = MetatronClient::ManifestationAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ManifestationAttributes' do
    it 'should create an instact of ManifestationAttributes' do
      @instance.should be_a(MetatronClient::ManifestationAttributes) 
    end
  end
end

