=begin
Metatron Server

A primitive modelling bibliographic metadata

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ManifestationRelationships
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ManifestationRelationships' do
  before do
    # run before each test
    @instance = SwaggerClient::ManifestationRelationships.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ManifestationRelationships' do
    it 'should create an instact of ManifestationRelationships' do
      @instance.should be_a(SwaggerClient::ManifestationRelationships) 
    end
  end
  describe 'test attribute "contributors"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "assets"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "work"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

