=begin
Metatron Server

A primitive modelling bibliographic metadata

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::OneToOneRelationship
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OneToOneRelationship' do
  before do
    # run before each test
    @instance = SwaggerClient::OneToOneRelationship.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OneToOneRelationship' do
    it 'should create an instact of OneToOneRelationship' do
      @instance.should be_a(SwaggerClient::OneToOneRelationship) 
    end
  end
  describe 'test attribute "meta"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "links"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

