=begin
Metatron Server

A primitive modelling bibliographic metadata

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MetatronClient::WorkAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WorkAttributes' do
  before do
    # run before each test
    @instance = MetatronClient::WorkAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkAttributes' do
    it 'should create an instact of WorkAttributes' do
      @instance.should be_a(MetatronClient::WorkAttributes) 
    end
  end
  describe 'test attribute "titles"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "authors"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "isbns"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

