=begin
Metatron Server

A primitive modelling bibliographic metadata

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

# Common files
require 'metatron_ruby_client/api_client'
require 'metatron_ruby_client/api_error'
require 'metatron_ruby_client/version'
require 'metatron_ruby_client/configuration'

# Models
require 'metatron_ruby_client/models/asset'
require 'metatron_ruby_client/models/asset_attributes'
require 'metatron_ruby_client/models/asset_result_set'
require 'metatron_ruby_client/models/error'
require 'metatron_ruby_client/models/errors'
require 'metatron_ruby_client/models/item'
require 'metatron_ruby_client/models/item_result_set'
require 'metatron_ruby_client/models/links'
require 'metatron_ruby_client/models/manifestation'
require 'metatron_ruby_client/models/manifestation_attributes'
require 'metatron_ruby_client/models/manifestation_relationships'
require 'metatron_ruby_client/models/manifestation_result_set'
require 'metatron_ruby_client/models/meta'
require 'metatron_ruby_client/models/one_to_many_relationship'
require 'metatron_ruby_client/models/one_to_one_relationship'
require 'metatron_ruby_client/models/resource'
require 'metatron_ruby_client/models/work'
require 'metatron_ruby_client/models/work_attributes'
require 'metatron_ruby_client/models/work_relationships'
require 'metatron_ruby_client/models/work_result_set'

# APIs
require 'metatron_ruby_client/api/default_api'

module MetatronClient
  class << self
    # Customize default settings for the SDK using block.
    #   MetatronClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
